-- ====================================================
-- NOLÉYA MARKETPLACE — SUPABASE POSTGRESQL SCHEMA & SEED
-- ====================================================

CREATE TABLE IF NOT EXISTS noleya_users (
  id BIGSERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  role TEXT NOT NULL DEFAULT 'CUSTOMER',
  status TEXT NOT NULL DEFAULT 'active',
  must_change_password INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_sellers (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES noleya_users(id) ON DELETE CASCADE,
  business_name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  whatsapp_number TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  region TEXT NOT NULL,
  city TEXT,
  address TEXT,
  bio TEXT,
  logo_url TEXT,
  banner_url TEXT,
  commission_rate NUMERIC DEFAULT 0.05,
  status TEXT NOT NULL DEFAULT 'pending',
  delivery_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_seller_applications (
  id BIGSERIAL PRIMARY KEY,
  full_name TEXT NOT NULL,
  business_name TEXT NOT NULL,
  whatsapp_number TEXT NOT NULL,
  email TEXT NOT NULL,
  region TEXT NOT NULL,
  city TEXT,
  category_name TEXT NOT NULL,
  product_samples TEXT,
  delivery_options TEXT,
  social_media TEXT,
  business_description TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_categories (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  image_url TEXT,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_regions (
  id BIGSERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  capital TEXT
);

CREATE TABLE IF NOT EXISTS noleya_products (
  id BIGSERIAL PRIMARY KEY,
  seller_id BIGINT NOT NULL REFERENCES noleya_sellers(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES noleya_categories(id),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  price_ghs NUMERIC NOT NULL,
  compare_price_ghs NUMERIC,
  stock_quantity INTEGER NOT NULL DEFAULT 1,
  is_unlimited_stock INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'published',
  is_featured INTEGER NOT NULL DEFAULT 0,
  sku TEXT,
  specifications TEXT,
  delivery_info TEXT,
  views_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_product_images (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES noleya_products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  alt_text TEXT,
  display_order INTEGER DEFAULT 0,
  is_primary INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_order_enquiries (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT REFERENCES noleya_products(id) ON DELETE SET NULL,
  seller_id BIGINT REFERENCES noleya_sellers(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_location TEXT,
  quantity INTEGER DEFAULT 1,
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'direct_inquiry',
  status TEXT NOT NULL DEFAULT 'lead_initiated',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_foundation_impact (
  id BIGSERIAL PRIMARY KEY,
  initiative_name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  metric_label TEXT,
  metric_value TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS noleya_audit_logs (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT,
  user_email TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS and public read for products, categories, regions, impact, settings
ALTER TABLE noleya_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_sellers ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_foundation_impact ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_order_enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_seller_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE noleya_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read published products" ON noleya_products FOR SELECT USING (status = 'published');
CREATE POLICY "Allow public read product images" ON noleya_product_images FOR SELECT USING (true);
CREATE POLICY "Allow public read categories" ON noleya_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read regions" ON noleya_regions FOR SELECT USING (true);
CREATE POLICY "Allow public read approved sellers" ON noleya_sellers FOR SELECT USING (true);
CREATE POLICY "Allow public read impact" ON noleya_foundation_impact FOR SELECT USING (true);
CREATE POLICY "Allow public read settings" ON noleya_site_settings FOR SELECT USING (true);
CREATE POLICY "Allow public insert order inquiries" ON noleya_order_enquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert seller applications" ON noleya_seller_applications FOR INSERT WITH CHECK (true);

-- Allow service role full access
CREATE POLICY "Service role full access products" ON noleya_products FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access images" ON noleya_product_images FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access categories" ON noleya_categories FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access regions" ON noleya_regions FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access sellers" ON noleya_sellers FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access impact" ON noleya_foundation_impact FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access settings" ON noleya_site_settings FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access inquiries" ON noleya_order_enquiries FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access applications" ON noleya_seller_applications FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access users" ON noleya_users FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access logs" ON noleya_audit_logs FOR ALL TO service_role USING (true);

INSERT INTO noleya_users (id, email, username, password_hash, salt, name, phone, role, status, must_change_password) VALUES (1, 'FishyBetty', 'FishyBetty', '1fb17bcedb29cfd33699df9eb073d5f9efa21fd0d03e275f3a0a6030594fa35811ae30aada53d15204f98f071f404b70ebcc434a62336836f98813ec6f1df6cc', '37cb853fa12a923cda3a66732afa6234a0867da0e1e875b26a06b23df35450f1', 'Noléya Executive Admin', '0545811197', 'OWNER', 'active', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_users (id, email, username, password_hash, salt, name, phone, role, status, must_change_password) VALUES (2, 'luex@noleya.org', NULL, '70f1274e7ae52b3d3a83b31d74d2eb039471374d9d729d12f991fa28311a3993c58ef7ee19455a7a11dca13aef3a796950913cccb4d2ac5b1f76e530cf916a1b', '00864908f66a201cce8dadee542a8ceee39f44ef1b62b7d79e8203dca1f93fa5', 'Luex Healthcare Official', '0545811197', 'SELLER', 'active', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_users (id, email, username, password_hash, salt, name, phone, role, status, must_change_password) VALUES (3, 'etleather@noleya.org', NULL, 'f435b522ce0f8b37b7ec4ff227edfd992e908907566316ab3e42fc2cae61700736292ef7d9d4bd156397068f3c8e498463758ab2e11f297b108a039ed36da928', '461f32ade69b6d1d348ed936110e25049245044a9b52d4527d2c494bd1c2307f', 'ET Leather Collections Manager', '0204822847', 'SELLER', 'active', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_sellers (id, user_id, business_name, slug, whatsapp_number, phone, email, region, city, address, bio, commission_rate, status, delivery_notes) VALUES (1, 2, 'Luex Healthcare & Hollywood Nutritions', 'luex-healthcare-ghana', '0545811197', '0545811197', 'orders@luexhealthcare.com', 'Greater Accra', 'Accra', 'Osu / Oxford Street, Accra', 'Official distributor of Hollywood Nutritions, Luex Healthcare, and clinically formulated health & personal care products in Ghana.', 0.05, 'approved', 'Nationwide doorstep delivery via standard dispatch rider in Accra (same day/24h) and VIP courier across other regions (48h).') ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_sellers (id, user_id, business_name, slug, whatsapp_number, phone, email, region, city, address, bio, commission_rate, status, delivery_notes) VALUES (2, 3, 'ET Leather Collections Ghana', 'et-leather-collections', '0204822847', '0204822847', 'etleatherbags@gmail.com', 'Greater Accra', 'East Legon, Accra', 'Lagos Avenue, East Legon, Accra', 'Accra premier purveyor of luxury POMBELL designer handbags, textured satchels, executive totes, and leather accessories.', 0.05, 'approved', 'Free pickup in East Legon. Same-day delivery across Accra & Tema. Intercity express parcel delivery to Kumasi, Takoradi, Cape Coast, and Tamale.') ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_sellers (id, user_id, business_name, slug, whatsapp_number, phone, email, region, city, address, bio, commission_rate, status, delivery_notes) VALUES (3, 1, 'Noléya Curated Hampers & Personalized Gifts', 'noleya-curated-hampers', '0545811197', '0545811197', 'Noléyafoundation@gmail.com', 'Greater Accra', 'Accra', 'Airport Residential, Accra', 'Bespoke corporate gift hampers, personalized keepsakes, and luxury occasion packages connecting impact to joy.', 0.05, 'approved', 'Same-day delivery across Accra & Tema; reliable courier dispatch across all 16 regions of Ghana.') ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_sellers (id, user_id, business_name, slug, whatsapp_number, phone, email, region, city, address, bio, commission_rate, status, delivery_notes) VALUES (4, 1, 'Crime Scene Clothing Line', 'crime-scene-streetwear', '0204822847', '0204822847', 'Noléyafoundation@gmail.com', 'Greater Accra', 'Accra', 'Osu & East Legon, Accra', 'Contemporary Ghanaian conceptual streetwear brand exploring truth, evidence, and raw narrative style.', 0.05, 'approved', 'Fast nationwide delivery via VIP parcel and local rider courier.') ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (1, 'Health & Wellness', 'health-wellness', 'Vitamins, supplements, hair care, and nutritional formulas.', NULL, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (2, 'Bags & Handbags', 'bags', 'Luxury leather handbags, satchels, totes, wallets and accessories.', NULL, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (3, 'Beauty & Personal Care', 'beauty', 'Skin glow formulas, derma rollers, and rejuvenation essentials.', NULL, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (4, 'Fashion', 'fashion', 'Apparel, artisanal wear, and Ghanaian crafted fashion.', NULL, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (5, 'Shoes & Footwear', 'shoes', 'Handcrafted leather shoes, sandals, and formal footwear.', NULL, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (6, 'Jewellery & Watches', 'jewellery', 'Authentic Ghanaian jewellery, beads, and luxury timepieces.', NULL, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (7, 'Electronics', 'electronics', 'Phones, audio gear, and everyday electronic accessories.', NULL, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (8, 'Home & Lifestyle', 'home', 'Living room decor, handcrafted homeware, and lifestyle goods.', NULL, 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (9, 'Gifts & Hampers', 'gifts', 'Curated hampers, corporate gifting, and special occasion presents.', NULL, 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_categories (id, name, slug, description, image_url, display_order) VALUES (10, 'Food & Groceries', 'food', 'Organic honey, local snacks, and authentic Ghanaian provisions.', NULL, 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (1, 'Greater Accra', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (2, 'Ashanti Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (3, 'Central Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (4, 'Eastern Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (5, 'Western Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (6, 'Western North', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (7, 'Volta Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (8, 'Oti Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (9, 'Northern Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (10, 'Savannah Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (11, 'North East Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (12, 'Upper East Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (13, 'Upper West Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (14, 'Bono Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (15, 'Bono East Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_regions (id, name, capital) VALUES (16, 'Ahafo Region', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (1, 1, 1, 'Kirkland Signature Minoxidil 5% Topical Solution (Men Hair Regrowth)', 'kirkland-minoxidil-5-hair-regrowth', 'Clinically proven extra-strength topical solution designed to reactivate shrunken hair follicles and stimulate new hair and beard growth. Comes with original precision dropper applicator. Recommended for daily application.', 0, NULL, 35, 0, 'published', 1, NULL, '{"Volume":"60 ml (1 Bottle / 1 Month Supply)","Active Ingredient":"Minoxidil USP 5% Extra Strength","Formulation":"Unscented Topical Solution with Calibrated Dropper","Target Area":"Crown & Beard Hair Follicles","Origin":"USA (Kirkland Signature)"}', 'Same-day delivery across Greater Accra. 24–48 hours nationwide via VIP courier.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (2, 1, 1, 'Complete Beard & Hair Regrowth System (Minoxidil 5% + Biotin 10,000mcg + Derma Roller)', 'complete-beard-hair-regrowth-system', 'The definitive all-in-one grooming regimen for hair regrowth and thick beard development. Combining collagen-stimulating micro-needling, essential high-potency Biotin cellular nutrition, and extra-strength 5% Minoxidil solution.', 0, NULL, 20, 0, 'published', 1, NULL, '{"Included In Box":"Kirkland Minoxidil 5% (60ml), Puritan''s Pride Biotin 10,000mcg (50 softgels), 540 Micro-Needle Derma Roller System","Treatment Cycle":"Full 30-Day Intensive Activation Bundle","Needle Length":"0.5mm Titanium Micro-needles","Biotin Strength":"Ultra Mega 10,000 mcg Vitamin B7"}', 'Fast nationwide delivery with tamper-proof packaging.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (3, 1, 1, 'MET-Rx Creatine 4200 Muscle Strength & Power Booster (240 Capsules)', 'met-rx-creatine-4200-capsules', 'MET-Rx Creatine 4200 provides 4.2g of pure creatine monohydrate per serving to boost explosive power, elevate workout threshold, and stimulate lean muscle growth during gym resistance workouts.', 0, NULL, 18, 0, 'published', 1, NULL, '{"Quantity":"240 Fast-Release Capsules","Creatine Dose":"4,200 mg Pure Creatine Monohydrate per serving","Key Benefits":"Boosts Muscle Strength, Power, and Athletic Recovery","Brand":"MET-Rx"}', 'Available for immediate dispatch from Accra warehouse.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (4, 1, 1, 'Slim Smart Raspberry Ketones Appetite Control & Metabolism (60 Capsules)', 'slim-smart-raspberry-ketones', 'Clinically formulated with African Mango and concentrated green tea polyphenols to help curb food cravings, improve metabolic rate, and assist in trimming stubborn belly fat naturally.', 0, NULL, 25, 0, 'published', 0, NULL, '{"Form":"60 Vegan Capsules","Active Botanical Blend":"Raspberry Ketones, African Mango, Green Tea Extract","Benefits":"Appetite Control, Fat Reduction, Thermogenic Metabolism","Brand":"Hollywood Nutritions / Luex"}', 'Doorstep dispatch in Accra, Kumasi, Takoradi, and Sunyani.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (5, 1, 1, 'Free Flex Ultra Comprehensive Joint Health Therapy (60 Capsules)', 'free-flex-ultra-joint-health', 'Move with strength and live without limits. Free Flex Ultra combines 19 pharmaceutical-grade natural ingredients including shark cartilage and green lipped mussel to alleviate joint stiffness and regenerate joint cartilage.', 0, NULL, 30, 0, 'published', 0, NULL, '{"Key Ingredients":"Glucosamine, Chondroitin Sulphate, MSM, Green Lipped Sea Mussel, Shark Cartilage","Total Active Nutrients":"19 Joint Health Ingredients","Primary Focus":"Cartilage Protection, Ease Chronic Pain, Joint Lubrication","Origin":"Luex Healthcare / Hollywood Nutritions"}', 'Available nationwide with secure courier delivery.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (6, 1, 1, 'Ferrolex Syrup Blood Tonic Fortified with Iron, Folic Acid, B12 & Zinc (250ml)', 'ferrolex-blood-tonic-syrup-250ml', 'Complete haematinic therapy for iron deficiency anaemia. Fortified with essential blood-building micronutrients including zinc and B12. Highly recommended for expectant mothers, convalescent recovery, and growing youths.', 0, NULL, 50, 0, 'published', 0, NULL, '{"Volume":"250 ml Liquid Tonic","Key Formula":"Ferrous Glycine Sulphate 300mg/10ml, Folic Acid 1mg, Iron 53mg, Zinc 80mg, Vitamin B12 5mcg","Indication":"Anaemia Therapy, Energy Rejuvenation, Pregnancy & Growth Support","Flavor":"Natural Sweet Orange"}', 'Accra express delivery within 4 hours. Available nationwide.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (7, 1, 1, 'Slim Smart Thermogenic Fat Burner Powered by Plants', 'slim-smart-fat-burner-powder', 'Harness the ancient potency of Ayurvedic thermogenic herbs. Accelerates fat breakdown, flushes excess bloating fluids, and promotes smooth digestive wellness.', 0, NULL, 22, 0, 'published', 0, NULL, '{"Formulation":"100% Natural Botanical Herbal Thermogenic Powder","Ingredients":"Garcinia Cambogia, Ginger Root, Turmeric, Long Pepper, Green Tea, Haritaki, Fennel Seeds","Action":"Accelerates Metabolism, Relieves Bloating, Clean Digestion"}', 'Nationwide shipping from Accra.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (8, 1, 3, 'Nutri-Glow Radiate & Rejuvenate Hair, Skin & Nails Formula (30 Capsules)', 'nutri-glow-radiate-rejuvenate-capsules', 'Pharmacist-recommended beauty-from-within formula. Contains 32 synergistic vitamins and botanicals including glutathione and grape seed extract to even out skin tone, enhance elasticity, and fortify nail health.', 0, NULL, 40, 0, 'published', 1, NULL, '{"Count":"30 Once-a-Day Capsules","Key Actives":"Biotin, Grape Seed Extract, Glutathione, Vitamin A, Vitamin C, Vitamin E","Total Nutrients":"32 Premium Bioactive Ingredients","Benefits":"Luminous Complexion, Strong Nails, Thick Healthy Hair"}', 'Dispatched in discreet protective packaging across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (9, 1, 1, 'Ayurleaf Body Mass Weight Gainer Herbal Supplement (60 Capsules)', 'ayurleaf-weight-gainer-60-capsules', 'A gentle and holistic Ayurvedic herbal compound formulated to support healthy appetite stimulation, enhance metabolic absorption, and help underweight individuals build natural muscular body mass.', 0, NULL, 28, 0, 'published', 0, NULL, '{"Capsule Count":"60 Herbal Capsules","Certification":"GMP Certified Ayurvedic Formulation","Primary Action":"Appetite Stimulation, Nutrient Uptake, Healthy Body Mass"}', 'Fast delivery across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (10, 1, 1, 'Vita-Fizz Immune Support 1000mg Vitamin C + Zinc (20 Effervescent Tablets)', 'vita-fizz-immune-support-tablets', 'Supercharge your natural defenses with Vita-Fizz. Fast-acting effervescent drink providing 1000mg Vitamin C, Zinc, and Ayurvedic adaptogens to reduce fatigue and support mental vitality.', 0, NULL, 60, 0, 'published', 1, NULL, '{"Tablets":"20 Effervescent Dissolvable Tablets","Potency":"1000 mg Vitamin C + High Bioavailability Zinc","Herbal Complex":"Ashwagandha, Tulsi, Brahmi Leaves, Amla, Ginger Root","Speed":"Fast Dissolution in Water in Under 30 Seconds"}', 'Accra same-day delivery. Nationwide shipping available.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (11, 1, 1, 'Hollywood Nutritions MAN-UP Advanced Vitality Formula (60 Capsules)', 'hollywood-nutritions-man-up-60-capsules', 'Empower your vitality, energy, and physical endurance. Crafted with premium natural adaptogens to promote healthy male circulation, stamina, and overall vigor.', 0, NULL, 24, 0, 'published', 0, NULL, '{"Count":"60 Capsules","Formula":"Maximum Strength Male Enhancement & Vitality Formula","Ingredients":"100% Pure & Potent Natural Botanical Extracts","Certification":"Made in USA, Distributed by Luex Healthcare"}', 'Discreet 100% private packaging and fast delivery.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (12, 1, 1, 'Hollywood Nutritions High-Potency Whey Protein Sachets (BCAA 7000+)', 'hollywood-nutritions-whey-protein-sachets', 'Build strength with every scoop. Rapid-digesting whey protein sachets enriched with over 7,000mg branched-chain amino acids for optimal post-workout recovery and muscular lean tone.', 0, NULL, 30, 0, 'published', 0, NULL, '{"Packaging":"Convenient Portable Multi-Serving Sachet Pack","Protein Content":"Ultra-Filtered Whey Protein Complex","Amino Acids":"7,000 mg BCAAs per serving","Function":"Rapid Muscle Recovery & Cellular Hydration"}', 'Available for immediate pickup or delivery.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (13, 2, 2, 'POMBELL F6723 Quilted Luxury Handbag & Wallet Set (33-13-23cm)', 'pombell-f6723-quilted-luxury-handbag', 'A masterclass in everyday luxury. The POMBELL F6723 features diamond-quilted leather, reinforced rolled carry handles, smooth zip entry, and an accompanying full-length continental wallet.', 0, NULL, 15, 0, 'published', 1, NULL, '{"Dimensions":"33 cm (L) x 13 cm (W) x 23 cm (H)","Model":"F6723","Texture":"Diamond Quilted Embossed Calfskin Leather","Set Inclusions":"Structured Handbag, Detachable Shoulder Strap, Continental Snap Wallet","Colorways":"Black, Olive Green, Mustard Yellow, Navy, Purple, Tan, Beige, Wine Red"}', 'Free delivery within East Legon, Accra. Nationwide shipping within 48 hours.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (14, 2, 2, 'POMBELL K3315 Structured Flap Handbag with Continental Purse (30-11-23cm)', 'pombell-k3315-structured-flap-handbag', 'Clean architectural lines and modern elegance. The K3315 offers an iconic trapezoidal envelope flap secured by a polished gold lock, complemented by a matching color-matched wallet.', 0, NULL, 14, 0, 'published', 1, NULL, '{"Dimensions":"30 cm x 11 cm x 23 cm","Model":"K3315","Hardware":"Brushed Gold Triangular Lock Mechanism","Interior":"Double Main Compartment with Center Zip Divider","Accessories":"Adjustable Crossbody Strap & Matching Designer Purse"}', 'Dispatched immediately from East Legon showroom.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (15, 2, 2, 'POMBELL F6698 Dual-Tone Colorblock Flap Handbag & Wallet (34-15-21cm)', 'pombell-f6698-colorblock-flap-handbag', 'Contemporary two-tone styling that turns heads. Spacious interior accommodates tablets, planners, and essentials with ease, accompanied by an executive matching wallet.', 0, NULL, 12, 0, 'published', 0, NULL, '{"Dimensions":"34 cm x 15 cm x 21 cm","Model":"F6698","Design":"Two-Tone Colorblock with Architectural Oval Lock","Included":"Tote Satchel, Crossbody Strap, Long Zip Wallet"}', 'Doorstep dispatch across Accra, Kumasi, and Takoradi.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (16, 2, 2, 'POMBELL K3312 Center-Clasp Structured Handbag & Wallet (30-13-24cm)', 'pombell-k3312-center-clasp-handbag', 'Distinguished by a contrasting color center tongue and decorative lock hardware, this versatile satchel brings refined sophistication to any business or formal occasion.', 0, NULL, 10, 0, 'published', 0, NULL, '{"Dimensions":"30 cm x 13 cm x 24 cm","Model":"K3312","Accent":"Contrast Center Flap with Teardrop Twist Clasp","Handle":"Sculpted Top Handle with Reinforced Edge Paint"}', 'Dispatched with protective dust bag.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (17, 2, 2, 'POMBELL F6702 Gold-Belt Accent Executive Handbag & Wallet (31-12-21cm)', 'pombell-f6702-gold-belt-executive-handbag', 'Impeccable executive silhouette embellished with twin polished gold belt ornaments across the front panel. Includes matching continental wallet and shoulder strap.', 0, NULL, 16, 0, 'published', 0, NULL, '{"Dimensions":"31 cm x 12 cm x 21 cm","Model":"F6702","Detail":"Twin Buckle Gold-Tone Belt Strap Accents","Structure":"Stiffened Base with Protective Metal Feet"}', 'Nationwide courier delivery.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (18, 2, 2, 'POMBELL 3313 V-Flap Braided Chain Handbag & Long Wallet (33-12-19cm)', 'pombell-3313-v-flap-chain-handbag', 'One of POMBELL''s most coveted designs. Features a striking chevron V-flap bordered with dark gunmetal braided chainwork, complemented by an opulent curb-chain handle.', 0, NULL, 18, 0, 'published', 1, NULL, '{"Dimensions":"33 cm x 12 cm x 19 cm","Model":"3313","Flap":"V-Cut Envelope with Inset Braided Curb Chain","Handle":"Leather-Wrapped Curb Chain Top Handle","Set":"Handbag, Crossbody Strap, Full-Length Continental Purse"}', 'Accra same-day delivery. Secure regional courier.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (19, 2, 2, 'POMBELL K8806# Basket-Weave Textured Leather Handbag & Wallet (32-12-23cm)', 'pombell-k8806-textured-woven-handbag', 'Artisanal texture meets executive poise. The textured basket-weave lower panel contrasts harmoniously against silky-smooth calfskin leather, anchored by a signature oval clasp.', 0, NULL, 15, 0, 'published', 1, NULL, '{"Dimensions":"32 cm x 12 cm x 23 cm","Model":"K8806#","Material":"Intricate Basket-Weave Textured Lower Body & Smooth Calfskin Flap","Clasp":"Polished Oval Twist-Lock","Wallet":"Matching Zip-Around Leather Continental Wallet"}', 'Available for immediate delivery across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (20, 2, 2, 'POMBELL F6727 Executive Tote Bag with Signature Tag & Wallet (31-14-24cm)', 'pombell-f6727-executive-tote-handbag', 'Spacious, commanding, and impeccably finished. Designed for professional women who carry their world with grace. Accommodates paperwork, makeup kits, and everyday essentials.', 0, NULL, 11, 0, 'published', 0, NULL, '{"Dimensions":"31 cm x 14 cm x 24 cm","Model":"F6727","Style":"Structured Executive Carryall Tote","Details":"Vertical Chevron Topstitching, Debossed Leather Hangtag, Matching Clutch Wallet"}', 'Free shipping on orders within Greater Accra.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (21, 2, 2, 'POMBELL L18005 Braided Handle Satchel Handbag & Wallet (30-13-22cm)', 'pombell-l18005-braided-handle-satchel', 'Inspired by classic vintage doctor satchels, featuring an exquisite tubular hand-braided arch handle and a modern hinged top frame clasp for effortless access.', 0, NULL, 13, 0, 'published', 0, NULL, '{"Dimensions":"30 cm x 13 cm x 22 cm","Model":"L18005","Handle":"Artisanal Hand-Braided Rounded Arch Top Handle","Closure":"Top Push-Button Hinged Frame Clasp"}', 'Prompt doorstep delivery via dispatch rider.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (22, 2, 2, 'POMBELL F6685 Envelope Flap Shoulder Bag & Mini Chain Pouch (31-14-33cm)', 'pombell-f6685-envelope-flap-shoulder-bag', 'An ingenious 2-in-1 combo. A sleek envelope flap shoulder bag accompanied by a detachable mini crossbody pouch on a golden curb chain for quick evening transitions.', 0, NULL, 14, 0, 'published', 0, NULL, '{"Dimensions":"31 cm x 14 cm x 33 cm","Model":"F6685","Versatility":"2-in-1 Dual Bag Set (Main Shoulder Bag + Detachable Mini Chain Pouch)","Strap":"Wide Ergonomic Leather Shoulder Strap"}', 'Available across all regions in Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (23, 2, 2, 'POMBELL F6716 Chain-Link Strap Crossbody Shoulder Bag & Wallet (30-12-22cm)', 'pombell-f6716-chain-strap-shoulder-bag', 'A striking statement handbag engineered for seamless transitions from day meetings to evening dinners. Includes matching zippered wallet and detachable long strap.', 0, NULL, 15, 0, 'published', 0, NULL, '{"Dimensions":"30 cm x 12 cm x 22 cm","Model":"F6716","Chain":"High-Gloss Gunmetal Shoulder Chain with Leather Shoulder Rest","Clasp":"Heavy-Duty Rectangular Center Buckle"}', 'Fast delivery across Greater Accra and beyond.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (24, 2, 2, 'POMBELL F6700 Hand-Stitched Flap Chain Bag with Half-Moon Mini Bag (31-13-20cm)', 'pombell-f6700-stitched-flap-chain-bag', 'Unique artisanal whipstitching accents the contour of the front flap. Comes packaged with an adorable half-moon mini bag that can be carried separately or hooked as a charm.', 0, NULL, 12, 0, 'published', 0, NULL, '{"Dimensions":"31 cm x 13 cm x 20 cm","Model":"F6700","Craftsmanship":"Edge Whipstitch Hand Detail along Flap Border","Bonus Item":"Detachable Half-Moon Petite Saddle Bag"}', 'Dispatched with care from East Legon, Accra.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (25, 2, 2, 'Architectural Geometric Winged Leather Handbag & Wallet Set', 'architectural-geometric-winged-handbag', 'A daring, sculptural silhouette that commands attention wherever you go. Precision diagonal chevron leather cuts fold outward into flared wings, finished with an artisan braided handle.', 0, NULL, 10, 0, 'published', 1, NULL, '{"Design":"Origami-Inspired Winged Silhouette with Chevron Paneling","Material":"Full Grain Pebble Leather Body with Smooth Trim","Handle":"Hand-Braided Corded Arch Top Handle","Accessories":"Adjustable Shoulder Strap & Matching Continental Zip Wallet"}', 'Premium nationwide delivery in protective storage bag.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (26, 2, 2, 'POMBELL Classic Dome Bowling Satchel & Wallet with Crossbody Strap', 'pombell-classic-dome-bowling-satchel', 'A silhouette inspired by timeless Parisian luxury travel luggage. Spacious curved dome opens wide for effortless packing, secured by dual heavy-duty zips and a turnlock front accent.', 0, NULL, 16, 0, 'published', 1, NULL, '{"Silhouette":"Classic Curved Dome Bowling Bag","Hardware":"Twist Padlock Front Lock and Extended Two-Way Zippers","Included":"Satchel, Adjustable Long Strap, Full-Length Continental Wallet","Colors":"Olive Green, Dusty Lavender, Burgundy, Camel Tan, Sky Blue, Noir Black, Espresso Brown"}', 'Same day dispatch in Greater Accra.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (27, 2, 2, 'POMBELL L18010 Asymmetric Wave-Flap Top Handle Handbag & Wallet (29-14-20cm)', 'pombell-l18010-asymmetric-flap-handbag', 'Break away from symmetry with the striking L18010. Its organic wave flap contours down into a vertical keyhole twist lock, highlighted by contrast edge trim.', 0, NULL, 14, 0, 'published', 0, NULL, '{"Dimensions":"29 cm x 14 cm x 20 cm","Model":"L18010","Cut":"Dynamic Asymmetric Wave Front Flap with Contrast Binding","Lock":"Modern Vertical Keyhole Twist Latch","Wallet":"Matching Snap-Button Continental Leather Wallet"}', 'Fast delivery across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (28, 2, 2, 'ET Leather Collections Seasonal Showcase Lineup', 'et-leather-collections-showcase', 'Explore the full range of authentic ET Leather fashion bags available in Accra. Choose from rich hues in olive green, vibrant yellow, royal purple, burgundy, and classic midnight black.', 0, NULL, 25, 0, 'published', 0, NULL, '{"Collection":"ET Leather Fashion Bags Verified Accra Inventory","Varieties":"Quilted Luxury, Top-Handle Satchels, Flap Shoulder Bags, Totes","Origin":"Guaranteed Genuine ET Leather Fashion Bags Stock"}', 'Immediate pickup in East Legon or courier dispatch nationwide.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (29, 3, 9, 'Personalized Bamboo Journal & MenBense Leather Wallet Executive Hamper', 'personalized-bamboo-journal-leather-wallet-executive-hamper', 'A bespoke executive gift hamper crafted for leaders, thinkers, and milestone celebrations. Features an eco-friendly bamboo wood spiral hardcover diary laser-engraved with customized name and inspirational quote, paired with a matching natural bamboo ballpoint stylus pen and a premium MenBense bifold leather wallet, artfully presented on shredded crimson paper in a luxury gift box.', 0, NULL, 15, 0, 'published', 1, 'GFT-BAMB-WAL-001', '{"Material":"Natural Bamboo Wood & MenBense Faux Leather","Includes":"Personalized Bamboo Journal, Bamboo Stylus Pen, MenBense Bifold Wallet, Luxury Gift Hamper","Customization":"Laser engraved name & personalized quote","Packaging":"Rigid hamper box with red paper shreds","Origin":"Crafted & Assembled in Accra, Ghana"}', 'Same-day or next-day delivery in Accra & Tema. 24-48 hours delivery across all other regions of Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (30, 3, 9, '"Half His Deen & Half Her Deen" Islamic Couple Mug Set', 'half-his-deen-half-her-deen-islamic-couple-mug-set', 'Celebrate sacred union, Nikkah ceremonies, and anniversaries with this romantic two-piece ceramic mug set. Beautifully printed with intertwined hands illustration, delicate heart motifs, and custom husband & wife name personalization ("Half His Deen" & "Half Her Deen"). Packaged in a display-window peach gift hamper box.', 0, NULL, 25, 0, 'published', 1, 'GFT-MUG-DEEN-002', '{"Material":"High-grade glazed white ceramic","Capacity":"11oz (325ml) per mug","Set Includes":"2 Matching Mugs (Half His Deen / Half Her Deen)","Care":"Microwave & Dishwasher Safe, Sublimation Print","Packaging":"Window display gift hamper box"}', 'Carefully bubble-wrapped and dispatched across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (31, 3, 9, 'Royal Blue Executive 3-Piece Thermal Flask & Journal Gift Set', 'royal-blue-executive-thermal-flask-journal-set', 'A stylish corporate and personal gifting curation in striking matte royal blue. Includes a 500ml double-wall vacuum insulated stainless steel water bottle with custom name engraving, a coordinated royal blue faux leather notebook with ribbon bookmark, and a matching royal blue metallic stylus pen.', 0, NULL, 20, 0, 'published', 0, 'GFT-BLUE-EXEC-003', '{"Thermal Flask":"500ml 304 Food-grade Stainless Steel (Keeps hot 12h / cold 24h)","Notebook":"A5 Lined Premium Leatherette Journal","Pen":"Dual-function metal ballpoint & touch stylus","Color":"Royal Blue Matte Finish","Customization":"Laser engraved recipient name on all 3 items"}', 'Available for immediate dispatch nationwide.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (32, 3, 9, 'Men''s Heritage Waffle Polo & Matelot Fragrance Luxury Hamper', 'mens-heritage-waffle-polo-matelot-fragrance-hamper', 'An all-in-one men''s lifestyle curation featuring a classic cream waffle-knit 100% cotton polo shirt, an exquisite Matelot Eau de Parfum in a nautical striped drawstring pouch, a designer black leather wallet with polished gold bit buckle, and an adjustable woven/leather belt.', 0, NULL, 12, 0, 'published', 1, 'GFT-MEN-POLO-004', '{"Polo Shirt":"100% Cotton Textured Waffle Polo (XL relaxed fit)","Fragrance":"Matelot Eau de Parfum with striped keepsake bag","Accessories":"Designer bifold black wallet + matching belt","Packaging":"Heavy kraft gift box with red shredded paper lining"}', 'Dispatched with care from Accra to all regions.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (33, 3, 9, 'Burgundy Textured Polo & Monogrammed Keepsake Gift Box', 'burgundy-textured-polo-monogrammed-keepsake-gift-box', 'A rich burgundy themed gift curation featuring a textured breathable knit polo shirt, a personalized glossy ceramic mug with custom name typography, an engraved bamboo & leather keychain, and a designer bifold wallet with snap clasp closure.', 0, NULL, 15, 0, 'published', 0, 'GFT-BURG-POLO-005', '{"Polo":"Burgundy textured breathable waffle-knit","Mug":"11oz customized monogram ceramic mug","Keychain":"Bamboo wood & genuine leather key tag","Wallet":"Embossed pattern bifold with snap lock"}', 'Dispatched via trusted courier nationwide.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (34, 3, 9, 'Newborn Baby Welcome & Essential Care Deluxe Hamper', 'newborn-baby-welcome-essential-care-deluxe-hamper', 'The ideal welcoming gift for new mothers and newborn babies in Ghana. Packed with doctor-recommended gentle baby essentials including Flora Kids gentle protection diapers, Softcare premium baby diapers, Cussons Baby Soft & Smooth moisturizing lotion, Cussons Baby talc powder, Cussons gentle cleansing bars, and Softcare sensitive baby wipes.', 0, NULL, 18, 0, 'published', 1, 'GFT-BABY-CARE-006', '{"Includes":"Flora Kids Diapers, Softcare Diapers, Cussons Baby Lotion, Powder, Soaps, Softcare Wipes","Skin Safety":"Hypoallergenic, dermatologist-tested for delicate newborn skin","Hamper Box":"Rigid white chest hamper with satin lining"}', 'Safe and hygienic nationwide delivery.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (35, 3, 9, 'Noir Royale Men''s Luxury Timepiece & Oud Fragrance Hamper', 'noir-royale-mens-timepiece-oud-fragrance-hamper', 'An executive statement gift box for discerning gentlemen. Showcases a monochrome vertical ribbed knit polo with gold accent lapel pin, Efolia Oud de Parfum Extreme (luxury Arabian oud fragrance), and a 3-piece stainless steel ensemble including a fluted bezel dress watch, an engraved bar link bracelet ("SKY"), and a tag pendant necklace.', 0, NULL, 10, 0, 'published', 1, 'GFT-NOIR-OUD-007', '{"Watch":"Fluted bezel stainless steel dress watch with date window","Jewelry":"Engraved bar link bracelet + matching dog-tag chain necklace","Fragrance":"Efolia Oud de Parfum Extreme (100ml)","Polo":"Black & white ribbed vertical stripe knit polo","Extras":"Gold lapel pin & greeting card"}', 'Express courier delivery across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (36, 3, 9, 'Lavender Romance Luxury Women''s Celebration Hamper', 'lavender-romance-luxury-womens-celebration-hamper', 'An enchanting celebration hamper designed for birthdays, Mother''s Day, and bridal milestones. Contains a chic pastel lilac crossbody bag with cultured pearl handle, a chilled bottle of Zomba Pink sparkling wine, an 18K gold-plated pendant necklace and stud earrings set, an electric ceramic mug warmer set ("Lucky"), a portable rechargeable cooling fan, a lavender plush hand towel, and gourmet confections.', 0, NULL, 12, 0, 'published', 1, 'GFT-LAV-WOM-008', '{"Handbag":"Pastel lilac vegan leather purse with pearl handle & crossbody strap","Sparkling Beverage":"Zomba Pink Sparkling Wine (750ml)","Jewelry":"18K Gold-plated triangular heart pendant & matching earrings","Tech & Comfort":"Electric mug warmer coaster + USB mini cooling fan + plush towel"}', 'Delivered securely in festive gift packaging.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (37, 3, 6, 'Royal Crown Custom Engraved 4-Piece Timepiece & Jewelry Suite', 'royal-crown-custom-engraved-4piece-timepiece-jewelry-suite', 'A stunning personal statement suite in polished stainless steel. Features a luxury dress watch with diamond hour markers and custom dial crown engraving ("Kafui 👑"), paired with a matching engraved bar link bracelet, an engraved tag necklace, and an engraved comfort-fit band ring, presented in a red velvet jewelry box.', 0, NULL, 15, 0, 'published', 1, 'JWL-ROYAL-CROWN-009', '{"Watch Movement":"High precision quartz with date magnification cyclops","Material":"Solid 316L Stainless Steel, tarnish-free & hypoallergenic","Set Includes":"Watch + Bar Link Bracelet + Pendant Necklace + Band Ring","Personalization":"Custom name & royal crown laser engraving","Box":"Luxe crimson velvet lined jewelry case"}', 'Nationwide registered delivery across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (38, 3, 9, '"The Boss" Executive Wooden Desk Stand & Leather Portfolio Set', 'the-boss-executive-wooden-desk-stand-leather-portfolio-set', 'Crafted for executives, pastors, entrepreneurs, and mentors. Includes a handcrafted solid pine desk organizer with smartphone / business card display stand laser-engraved with an inspirational scripture ("THE BOSS - May You Always Be Blessed, Philippians 4:19"), accompanied by an executive slate blue leather binder portfolio with magnetic clasp, a custom engraved metal pen, and an engraved wooden keychain.', 0, NULL, 14, 0, 'published', 0, 'GFT-BOSS-DESK-010', '{"Desk Organizer":"Natural solid wood pen holder & smartphone dock","Portfolio":"A5 Slate Blue Faux Leather Binder with magnetic buckle","Engraving":"Custom name and scripture dedication","Includes":"Desk Dock, A5 Binder, Ballpoint Pen, Wooden Keychain, Hamper Box"}', 'Same-day delivery in Accra. 24-48h nationwide.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (39, 3, 9, 'Blush Pink & Royal Blue Birthday Pamper Gift Box', 'blush-pink-royal-blue-birthday-pamper-gift-box', 'A vibrant celebration hamper featuring a dusty rose designer flap purse with gold monogram hardware, a 750ml bottle of Mega Non-Alcoholic Red Grape Sparkling Wine, a sparkling heart crystal tennis bracelet in gift box, Pink Love fragrance mist duo, blush pink slide sandals, and a 3-piece royal blue cotton towel set with satin ribbons.', 0, NULL, 12, 0, 'published', 0, 'GFT-PINK-BLUE-011', '{"Items Included":"Designer Handbag, Mega Non-Alcoholic Red Grape, Heart Tennis Bracelet, Slide Sandals, Towel Set, Perfume Set","Packaging":"Premium large rigid gift chest"}', 'Delivered securely in festive gift packaging.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (40, 3, 7, 'Bespoke Photo & Brand Custom Printed Shockproof Phone Cases', 'bespoke-photo-brand-custom-printed-shockproof-phone-cases', 'Transform your favorite memories, family portraits, artistic photography, or business logos into durable shockproof phone cases. Available for all iPhone models (iPhone 11 through iPhone 16 Pro Max) and Samsung Galaxy series. High-definition anti-scratch UV sublimation printing ensures vibrant, fade-proof colors with reinforced corner bumpers.', 0, NULL, 50, 0, 'published', 0, 'ELE-PHONE-CUSTOM-012', '{"Compatibility":"iPhone 11 - 16 Pro Max, Samsung Galaxy S & A Series","Print Quality":"HD UV Sublimation, Fade & Scratch Resistant","Protection":"Reinforced drop-proof TPU bumper with raised camera bezel"}', 'Custom printed and dispatched within 24-48 hours.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (41, 4, 4, 'Crime Scene "Evidence Never Lies" Washed Black Oversized Graphic Tee', 'crime-scene-evidence-never-lies-washed-black-oversized-tee', 'The signature heavyweight streetwear graphic tee from Crime Scene Clothing Line''s Case 001: "Truth in Silence" collection. Cut from 240 GSM pre-shrunk washed black cotton in an oversized streetwear silhouette. Features yellow crime scene tape and forensic chalk evidence markers on the back, and a minimalist chest print on the front.', 0, NULL, 30, 0, 'published', 1, 'CS-TEE-BLK-013', '{"Fabric":"100% Heavyweight Cotton (240 GSM)","Color":"Forensic Washed Black","Fit":"Relaxed / Oversized Streetwear Fit","Front Print":"Crime Scene Est. 2024 (Evidence Yellow)","Back Print":"Evidence Never Lies — Forensic Investigation Chalk Artwork","Origin":"Designed & Made in Ghana"}', 'Nationwide dispatch via rider and VIP parcel service.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (42, 4, 4, 'Crime Scene "Evidence Never Lies" Sand Beige Oversized Graphic Tee', 'crime-scene-evidence-never-lies-sand-beige-oversized-tee', 'Crafted in an earthy sand beige hue, this 240 GSM heavyweight oversized tee embodies the forensic investigative narrative: "Behind the tape lies more than just a scene. It holds the truth, the facts, and the justice that follows." Finished with distressed evidence graphic and crime scene tape back piece.', 0, NULL, 25, 0, 'published', 1, 'CS-TEE-BGE-014', '{"Fabric":"100% Combed Cotton (240 GSM)","Color":"Sand Beige / Desert Stone","Fit":"Oversized Streetwear Silhouette","Print":"Screen printed with distressed texture","Origin":"Accra, Ghana"}', 'Nationwide delivery across Ghana.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (43, 4, 4, 'Crime Scene "Truth Is Silent" Pure White Minimalist Streetwear Tee', 'crime-scene-truth-is-silent-pure-white-minimalist-tee', 'Clean, striking, and understated. Pure white heavyweight cotton tee featuring minimal "CRIME SCENE - EST 2026" chest typography, paired with a custom lower hem evidence case file patch with barcode detailing. Tagline: "For those who move in silence, but notice everything."', 0, NULL, 25, 0, 'published', 1, 'CS-TEE-WHT-015', '{"Fabric":"100% Ringspun Cotton (240 GSM)","Color":"Pure Optical White","Details":"Woven case file patch on lower hem, ribbed crewneck","Fit":"Modern boxy relaxed fit"}', 'Dispatched directly from Accra.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (44, 4, 4, 'Crime Scene "Observe. Record. Reveal." Washed Black Long-Sleeve Shirt', 'crime-scene-observe-record-reveal-washed-black-long-sleeve', 'Streetwear long-sleeve tee from the Evidence Collection. Crafted from soft-washed 240 GSM black cotton featuring distressed yellow typography down both sleeves ("OBSERVE. RECORD. REVEAL." on left sleeve, "SILENT SCENE. LOUD TRUTH." on right sleeve) and a full investigative evidence back print.', 0, NULL, 20, 0, 'published', 0, 'CS-LS-BLK-016', '{"Fabric":"100% Washed Cotton (240 GSM)","Sleeves":"Dual statement typography prints with ribbed wrist cuffs","Back Graphic":"Crime Scene Do Not Cross — Not Every Clue Is Obvious"}', 'Available for immediate dispatch nationwide.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (46, 4, 4, 'Crime Scene "Evidence Collection" Women''s Cropped Rib Tank Top', 'crime-scene-evidence-collection-womens-cropped-rib-tank-top', 'Edgy streetwear cropped tank top made from 220 GSM 2-way stretch rib-knit cotton. Features the iconic distressed crime scene evidence graphic on the front, minimal upper back branding, and a flattering body-contouring cropped cut.', 0, NULL, 22, 0, 'published', 0, 'CS-TNK-WOM-018', '{"Fabric":"220 GSM 2-Way Stretch Premium Ribbed Cotton","Fit":"Cropped Athletic / Streetwear Fit","Color":"Bone White / Ash","Print":"Front evidence marker composition with distressed caution tape"}', 'Available for immediate delivery across Ghana.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (47, 4, 4, 'Crime Scene "Follow The Evidence" Raw-Cut Sleeveless Muscle Streetwear Tee', 'crime-scene-follow-the-evidence-raw-cut-sleeveless-muscle-tee', 'High-impact sleeveless streetwear muscle tee featuring raw-cut open armholes, a relaxed oversized body, and the "Follow The Evidence, Not Opinions" forensic evidence front statement artwork. Perfect for gym sessions, concerts, and casual street culture.', 0, NULL, 20, 0, 'published', 0, 'CS-MSL-RAW-019', '{"Fabric":"240 GSM Heavyweight Cotton","Cut":"Raw-cut armhole edges with reinforced shoulder seams","Fit":"Boxy Oversized Streetwear Muscle Tee"}', 'Nationwide dispatch via rider and VIP parcel service.', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_products (id, seller_id, category_id, name, slug, description, price_ghs, compare_price_ghs, stock_quantity, is_unlimited_stock, status, is_featured, sku, specifications, delivery_info, views_count) VALUES (49, 4, 4, 'Crime Scene Clothing Line — Complete SS26 Capsule Collection Lookbook', 'crime-scene-clothing-line-complete-ss26-capsule-collection', 'Complete multi-piece bundle from Crime Scene Clothing Line''s SS26 "Truth in Silence" debut. Includes 1 Washed Black Graphic Tee, 1 Sand Beige Oversized Tee, 1 Long-Sleeve Streetwear Shirt, and 1 Heavyweight Fleece Hoodie. A complete streetwear wardrobe curation representing authenticity, evidence, and Ghanaian urban fashion.', 0, NULL, 8, 0, 'published', 1, 'CS-BNDL-SS26-021', '{"Bundle Includes":"1x Washed Black Tee, 1x Sand Beige Tee, 1x Long-Sleeve Shirt, 1x Heavyweight Fleece Hoodie","Sizes Available":"S, M, L, XL, XXL (Customizable per item)","Packaging":"Limited edition evidence bag collector''s box"}', 'Premium VIP boxed delivery across Ghana.', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (1, 1, '/uploads/products/img_12.39.41_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.39.41_pm.jpeg', 'Kirkland Signature Minoxidil 5% Topical Solution (Men Hair Regrowth)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (2, 2, '/uploads/products/img_12.39.42_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.39.42_pm.jpeg', 'Complete Beard & Hair Regrowth System (Minoxidil 5% + Biotin 10,000mcg + Derma Roller)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (3, 2, '/uploads/products/img_12.39.42_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.39.42_pm_1.jpeg', 'Complete Beard & Hair Regrowth System (Minoxidil 5% + Biotin 10,000mcg + Derma Roller)', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (4, 2, '/uploads/products/img_12.39.42_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.39.42_pm_2.jpeg', 'Complete Beard & Hair Regrowth System (Minoxidil 5% + Biotin 10,000mcg + Derma Roller)', 2, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (5, 3, '/uploads/products/img_12.39.42_pm_4.jpeg', '/uploads/products/thumbs/thumb_img_12.39.42_pm_4.jpeg', 'MET-Rx Creatine 4200 Muscle Strength & Power Booster (240 Capsules)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (6, 4, '/uploads/products/img_12.39.42_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_12.39.42_pm_3.jpeg', 'Slim Smart Raspberry Ketones Appetite Control & Metabolism (60 Capsules)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (7, 5, '/uploads/products/img_12.39.43_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.39.43_pm_1.jpeg', 'Free Flex Ultra Comprehensive Joint Health Therapy (60 Capsules)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (8, 6, '/uploads/products/img_12.39.43_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.39.43_pm_2.jpeg', 'Ferrolex Syrup Blood Tonic Fortified with Iron, Folic Acid, B12 & Zinc (250ml)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (9, 7, '/uploads/products/img_12.39.43_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_12.39.43_pm_3.jpeg', 'Slim Smart Thermogenic Fat Burner Powered by Plants', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (10, 8, '/uploads/products/img_12.39.43_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.39.43_pm.jpeg', 'Nutri-Glow Radiate & Rejuvenate Hair, Skin & Nails Formula (30 Capsules)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (11, 8, '/uploads/products/img_12.39.44_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_12.39.44_pm_3.jpeg', 'Nutri-Glow Radiate & Rejuvenate Hair, Skin & Nails Formula (30 Capsules)', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (12, 8, '/uploads/products/img_12.39.45_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.39.45_pm_1.jpeg', 'Nutri-Glow Radiate & Rejuvenate Hair, Skin & Nails Formula (30 Capsules)', 2, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (13, 9, '/uploads/products/img_12.39.44_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.39.44_pm_1.jpeg', 'Ayurleaf Body Mass Weight Gainer Herbal Supplement (60 Capsules)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (14, 10, '/uploads/products/img_12.39.44_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.39.44_pm_2.jpeg', 'Vita-Fizz Immune Support 1000mg Vitamin C + Zinc (20 Effervescent Tablets)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (15, 10, '/uploads/products/img_12.39.44_pm_4.jpeg', '/uploads/products/thumbs/thumb_img_12.39.44_pm_4.jpeg', 'Vita-Fizz Immune Support 1000mg Vitamin C + Zinc (20 Effervescent Tablets)', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (16, 10, '/uploads/products/img_12.39.45_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.39.45_pm.jpeg', 'Vita-Fizz Immune Support 1000mg Vitamin C + Zinc (20 Effervescent Tablets)', 2, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (17, 11, '/uploads/products/img_12.39.44_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.39.44_pm.jpeg', 'Hollywood Nutritions MAN-UP Advanced Vitality Formula (60 Capsules)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (18, 12, '/uploads/products/img_12.39.45_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.39.45_pm_2.jpeg', 'Hollywood Nutritions High-Potency Whey Protein Sachets (BCAA 7000+)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (19, 13, '/uploads/products/img_12.40.13_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.40.13_pm.jpeg', 'POMBELL F6723 Quilted Luxury Handbag & Wallet Set (33-13-23cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (20, 14, '/uploads/products/img_12.40.14_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.40.14_pm.jpeg', 'POMBELL K3315 Structured Flap Handbag with Continental Purse (30-11-23cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (21, 14, '/uploads/products/img_12.40.15_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.40.15_pm_1.jpeg', 'POMBELL K3315 Structured Flap Handbag with Continental Purse (30-11-23cm)', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (22, 15, '/uploads/products/img_12.40.14_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.40.14_pm_1.jpeg', 'POMBELL F6698 Dual-Tone Colorblock Flap Handbag & Wallet (34-15-21cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (23, 16, '/uploads/products/img_12.40.14_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.40.14_pm_2.jpeg', 'POMBELL K3312 Center-Clasp Structured Handbag & Wallet (30-13-24cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (24, 17, '/uploads/products/img_12.40.14_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_12.40.14_pm_3.jpeg', 'POMBELL F6702 Gold-Belt Accent Executive Handbag & Wallet (31-12-21cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (25, 18, '/uploads/products/img_12.40.17_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.40.17_pm.jpeg', 'POMBELL 3313 V-Flap Braided Chain Handbag & Long Wallet (33-12-19cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (26, 18, '/uploads/products/img_12.40.15_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.40.15_pm_2.jpeg', 'POMBELL 3313 V-Flap Braided Chain Handbag & Long Wallet (33-12-19cm)', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (27, 19, '/uploads/products/img_12.40.15_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.40.15_pm.jpeg', 'POMBELL K8806# Basket-Weave Textured Leather Handbag & Wallet (32-12-23cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (28, 20, '/uploads/products/img_12.40.16_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.40.16_pm_1.jpeg', 'POMBELL F6727 Executive Tote Bag with Signature Tag & Wallet (31-14-24cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (29, 21, '/uploads/products/img_12.40.16_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.40.16_pm_2.jpeg', 'POMBELL L18005 Braided Handle Satchel Handbag & Wallet (30-13-22cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (30, 22, '/uploads/products/img_12.40.16_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_12.40.16_pm_3.jpeg', 'POMBELL F6685 Envelope Flap Shoulder Bag & Mini Chain Pouch (31-14-33cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (31, 23, '/uploads/products/img_12.40.16_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.40.16_pm.jpeg', 'POMBELL F6716 Chain-Link Strap Crossbody Shoulder Bag & Wallet (30-12-22cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (32, 24, '/uploads/products/img_12.40.17_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.40.17_pm_1.jpeg', 'POMBELL F6700 Hand-Stitched Flap Chain Bag with Half-Moon Mini Bag (31-13-20cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (33, 25, '/uploads/products/img_12.40.17_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.40.17_pm_2.jpeg', 'Architectural Geometric Winged Leather Handbag & Wallet Set', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (34, 26, '/uploads/products/img_12.40.18_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_12.40.18_pm_1.jpeg', 'POMBELL Classic Dome Bowling Satchel & Wallet with Crossbody Strap', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (35, 26, '/uploads/products/img_12.40.18_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_12.40.18_pm_2.jpeg', 'POMBELL Classic Dome Bowling Satchel & Wallet with Crossbody Strap', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (36, 27, '/uploads/products/img_12.40.18_pm.jpeg', '/uploads/products/thumbs/thumb_img_12.40.18_pm.jpeg', 'POMBELL L18010 Asymmetric Wave-Flap Top Handle Handbag & Wallet (29-14-20cm)', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (37, 28, '/uploads/products/img_12.40.17_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_12.40.17_pm_3.jpeg', 'ET Leather Collections Seasonal Showcase Lineup', 0, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (38, 29, '/uploads/products/img_7.24.17_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_7.24.17_pm_1.jpeg', 'Personalized Bamboo Journal & MenBense Leather Wallet Executive Hamper', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (39, 30, '/uploads/products/img_7.24.17_pm.jpeg', '/uploads/products/thumbs/thumb_img_7.24.17_pm.jpeg', '"Half His Deen & Half Her Deen" Islamic Couple Mug Set', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (40, 31, '/uploads/products/img_7.24.18_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_7.24.18_pm_1.jpeg', 'Royal Blue Executive 3-Piece Thermal Flask & Journal Gift Set', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (41, 32, '/uploads/products/img_7.24.18_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_7.24.18_pm_2.jpeg', 'Men''s Heritage Waffle Polo & Matelot Fragrance Luxury Hamper', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (42, 33, '/uploads/products/img_7.24.18_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_7.24.18_pm_3.jpeg', 'Burgundy Textured Polo & Monogrammed Keepsake Gift Box', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (43, 34, '/uploads/products/img_7.24.18_pm_4.jpeg', '/uploads/products/thumbs/thumb_img_7.24.18_pm_4.jpeg', 'Newborn Baby Welcome & Essential Care Deluxe Hamper', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (44, 35, '/uploads/products/img_7.24.18_pm.jpeg', '/uploads/products/thumbs/thumb_img_7.24.18_pm.jpeg', 'Noir Royale Men''s Luxury Timepiece & Oud Fragrance Hamper', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (45, 36, '/uploads/products/img_7.24.19_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_7.24.19_pm_1.jpeg', 'Lavender Romance Luxury Women''s Celebration Hamper', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (46, 37, '/uploads/products/img_7.24.19_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_7.24.19_pm_2.jpeg', 'Royal Crown Custom Engraved 4-Piece Timepiece & Jewelry Suite', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (47, 38, '/uploads/products/img_7.24.19_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_7.24.19_pm_3.jpeg', '"The Boss" Executive Wooden Desk Stand & Leather Portfolio Set', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (48, 39, '/uploads/products/img_7.24.19_pm.jpeg', '/uploads/products/thumbs/thumb_img_7.24.19_pm.jpeg', 'Blush Pink & Royal Blue Birthday Pamper Gift Box', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (49, 40, '/uploads/products/img_7.24.20_pm.jpeg', '/uploads/products/thumbs/thumb_img_7.24.20_pm.jpeg', 'Bespoke Photo & Brand Custom Printed Shockproof Phone Cases', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (50, 41, '/uploads/products/img_8.47.03_pm.jpeg', '/uploads/products/thumbs/thumb_img_8.47.03_pm.jpeg', 'Crime Scene "Evidence Never Lies" Washed Black Oversized Graphic Tee', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (51, 41, '/uploads/products/img_8.47.01_pm.jpeg', '/uploads/products/thumbs/thumb_img_8.47.01_pm.jpeg', 'Crime Scene "Evidence Never Lies" Washed Black Oversized Graphic Tee - Detailed Specification & Tech Pack', 2, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (52, 42, '/uploads/products/img_8.47.03_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_8.47.03_pm_2.jpeg', 'Crime Scene "Evidence Never Lies" Sand Beige Oversized Graphic Tee', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (53, 43, '/uploads/products/img_8.53.11_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_8.53.11_pm_1.jpeg', 'Crime Scene "Truth Is Silent" Pure White Minimalist Streetwear Tee', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (54, 44, '/uploads/products/img_8.47.02_pm_2.jpeg', '/uploads/products/thumbs/thumb_img_8.47.02_pm_2.jpeg', 'Crime Scene "Observe. Record. Reveal." Washed Black Long-Sleeve Shirt', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (56, 46, '/uploads/products/img_8.47.03_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_8.47.03_pm_1.jpeg', 'Crime Scene "Evidence Collection" Women''s Cropped Rib Tank Top', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (57, 47, '/uploads/products/img_8.47.03_pm_3.jpeg', '/uploads/products/thumbs/thumb_img_8.47.03_pm_3.jpeg', 'Crime Scene "Follow The Evidence" Raw-Cut Sleeveless Muscle Streetwear Tee', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_product_images (id, product_id, image_url, thumbnail_url, alt_text, display_order, is_primary) VALUES (59, 49, '/uploads/products/img_8.47.02_pm_1.jpeg', '/uploads/products/thumbs/thumb_img_8.47.02_pm_1.jpeg', 'Crime Scene Clothing Line — Complete SS26 Capsule Collection Lookbook', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_foundation_impact (id, initiative_name, slug, summary, description, image_url, metric_label, metric_value, status, display_order) VALUES (1, 'Community Youth Tutoring & Literacy Program', 'community-youth-tutoring', 'Providing free after-school literacy tutoring, school textbooks, and learning kits to primary school pupils in disadvantaged communities.', 'Education is the most powerful equalizer. Noléya Foundation''s literacy initiative partners with trained university tutors to deliver structured reading, writing, and STEM tutoring to children who would otherwise lack supplemental academic support.', '/uploads/products/img_12.39.43_pm.jpeg', 'Children Tutored', '420+ Pupils', 'active', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_foundation_impact (id, initiative_name, slug, summary, description, image_url, metric_label, metric_value, status, display_order) VALUES (2, 'School Shoes & Uniforms Distribution Drive', 'school-shoes-uniforms-drive', 'Equipping vulnerable primary and junior high school pupils with durable school shoes, bags, and clean uniforms so they can attend school with dignity.', 'Countless bright students in rural districts face attendance barriers simply because they lack proper footwear or basic school uniforms. Our annual distribution drive directly equips children with locally crafted leather school shoes and uniforms.', '/uploads/products/img_12.40.16_pm_1.jpeg', 'Shoes & Uniforms Distributed', '850+ Pairs', 'active', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_foundation_impact (id, initiative_name, slug, summary, description, image_url, metric_label, metric_value, status, display_order) VALUES (3, 'Emergency Food & Nutrition Relief for Vulnerable Families', 'food-nutrition-relief', 'Delivering wholesome food staples, iron-fortified tonics, and nutritional packages to elderly citizens and impoverished families.', 'Noléya Foundation directly addresses food insecurity by delivering monthly staples, cooking essentials, and pediatric nutritional tonics to families facing acute economic distress in urban informal settlements.', '/uploads/products/img_12.39.43_pm_2.jpeg', 'Families Nourished', '1,200+ Households', 'active', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('site_title', 'Noléya Marketplace | Shop with purpose.', 'site_title') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('foundation_name', 'Noléya Foundation', 'foundation_name') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('foundation_tagline', 'Spreading joy. Restoring hope.', 'foundation_tagline') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('marketplace_tagline', 'Shop with purpose.', 'marketplace_tagline') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('hero_title', 'Discover Local Products. Empower Ghanaian Communities.', 'hero_title') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('hero_subtitle', 'Discover products from local businesses and independent sellers while supporting meaningful community initiatives through Noléya Foundation.', 'hero_subtitle') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('contact_phone_1', '0545811197', 'contact_phone_1') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('contact_phone_2', '0204822847', 'contact_phone_2') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('contact_email', 'Noléyafoundation@gmail.com', 'contact_email') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('contact_address', 'Accra, Greater Accra Region, Ghana', 'contact_address') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('foundation_relationship_text', 'Noléya Marketplace creates an opportunity for businesses and entrepreneurs to showcase their products while contributing to the work of Noléya Foundation. Every purchase empowers a local seller while helping fund community outreach, education, and healthcare support for vulnerable Ghanaians.', 'foundation_relationship_text') ON CONFLICT (key) DO UPDATE SET value = excluded.value;
INSERT INTO noleya_site_settings (key, value, description) VALUES ('seller_rules_text', '1. All products must be genuine, accurately photographed, and fairly priced.
2. Sellers must fulfill confirmed orders promptly with reliable contact information.
3. Prohibited, expired, or counterfeit goods will result in immediate permanent suspension.
4. Sellers commit to honoring the agreed 5% charitable contribution on confirmed marketplace orders to support Noléya Foundation community programs.', 'seller_rules_text') ON CONFLICT (key) DO UPDATE SET value = excluded.value;

SELECT setval('noleya_users_id_seq', (SELECT MAX(id) FROM noleya_users));
SELECT setval('noleya_sellers_id_seq', (SELECT MAX(id) FROM noleya_sellers));
SELECT setval('noleya_categories_id_seq', (SELECT MAX(id) FROM noleya_categories));
SELECT setval('noleya_regions_id_seq', (SELECT MAX(id) FROM noleya_regions));
SELECT setval('noleya_products_id_seq', (SELECT MAX(id) FROM noleya_products));
SELECT setval('noleya_product_images_id_seq', (SELECT MAX(id) FROM noleya_product_images));
SELECT setval('noleya_foundation_impact_id_seq', (SELECT MAX(id) FROM noleya_foundation_impact));
